### ISSUE TITLE
[Question] Filtering by Upvotes

### ISSUE THREAD

**Issue by Esco0823** [simoncools/Redditor-Public#1]
Hello, 

I was wondering if there was capability to filter the subreddit posts being posted to a Discord server channel by upvotes. For example if I wanted posts from r/abc fetched and posted every 20 minutes but only if they have at least 500 upvotes. 

Thanks.

**Comment by simoncools** [comment]
That's not something that is currently possible. This could be a good feature to add in the future but it will require major changes to the database and bot
